### ISSUE TITLE
Exit with non zero code when tests fail or have errors

### ISSUE THREAD

**Issue by joesantos418** [Orange-OpenSource/hurl#1440]
### Problem to solve

Currently, Hurl exits with a zero code returned even when tests fail or have errors, which causes some CI/CD pipelines like Bitbucket to not break even when they understand that tests didn't pass. 

### Proposal

Make Hurl exit with non zero codes when tests fail or have errors.

### Additional context and resources

This would be useful for users who use Bitbucket for CI/CD who wish to use Hurl for tests in their pipeline.

### Tasks to complete

- [ ] Define non zero code to be returned upon failure
- [ ] Define non zero code to be returned upon errors (in case of both, the code for errors would take precedence I imagine)
- [ ] Create PR that alters Hurl to returned the expected codes

**Comment by fabricereix** [comment]
Hi @joesantos418 
in order to reproduce the bug, could give us your command and your Hurl file?
thanks
