### ISSUE TITLE
Autotest generation from open-api-schema

### ISSUE THREAD

**Issue by c0ntradicti0n** [Orange-OpenSource/hurl#1619]
### Problem to solve

It's always hard to write as many tests as are useful. 
I have some more or less stupid python script, that creates hurl files from some openApi specification and does "property testing" on the api with those files (https://en.wikipedia.org/wiki/Software_testing#Property_testing)

```
import glob
import itertools
import json
import os
import re
import uuid
from pprint import pprint

import click
import jsonref
import regex as regex
import requests
import yaml
from dotenv import read_dotenv
from faker import Faker

Faker.seed(0)

tokens_dir = "tokens"
value_dir = "values/"
tests_dir = "tests/"
ignore_paths = []


def make_request_and_record_assertion(filename, method, url, headers, user_type, schema, param):
    global ignore_paths
    if method in ("post", "put", "patch"):
        request_body = create_dummy_request_body(schema)
    else:
        request_body = None

    with open(filename, "a") as file:

        response = requests.request(method.upper(), url, headers=headers, json=request_body)

        print(
            f"{response.status_code} {user_type :>15}  {method.upper():>6} to {url:>70}")
        file.write(f"{method.upper()} {url}\n\n")
        if "Authorization" in headers:
            file.write(f"Authorization: Bearer {headers['Authorization'].split()[1]}\n\n")

        if request_body:
            file.write(f"{json.dumps(request_body, indent=2)}\n\n")

        file.write(f"HTTP {response.status_code}\n\n")

        file.write("[Asserts]\n")

        try:
            result = json.loads(response.text)
            paths = disp_paths(result)

            for path in paths:
                if not any(ignore in path[0] for ignore in ignore_paths):
                    match path[1]:
                        case bool():
                            value = f"{str(path[1]).lower()}"
                        case str():
                            string = str(path[1]).replace('"', r'\"').replace("\n", r"\n")
                            value = f'"{string}"'
                        case int():
                            value = f"{path[1]}"
                        case None:
                            value = "null"

                    file.write(f"jsonpath \"{path[0]}\" ==  {value}\n")

        except json.decoder.JSONDecodeError:
            pass

        if "<!doctype" in response.text.lower():
            file.write("body contains \"Server Error (500)\"")
            file.write("\n\n")
            return

        file.write("\n\n")


def create_dummy_request_body(operation_schema):
    fake = Faker()

    request_body = {}
    schema = operation_schema["requestBody"]["content"]["application/json"]["schema"]

    for prop_name, prop_details in schema["properties"].items():
        if "allOf" in prop_details:
            parent_properties = prop_details["allOf"][0]["properties"]
            parent_object = {}
            for name, details in parent_properties.items():
                if details["type"] == "string":
                    if "format" in details and details["format"] == "uuid":
                        parent_object[name] = str(uuid.uuid4())
                    elif lookup_variable_value(name):
                        parent_object[name] = lookup_variable_value(name)[0]
                    else:
                        parent_object[name] = fake.text(max_nb_chars=255)
            request_body[prop_name] = parent_object
        elif prop_name == "title":
            request_body[prop_name] = fake.text(max_nb_chars=255)
        else:
            if prop_details["type"] == "string":
                if "format" in prop_details and prop_details["format"] == "uuid":
                    request_body[prop_name] = str(uuid.uuid4())
                elif lookup_variable_value(prop_name):
                    request_body[prop_name] = lookup_variable_value(prop_name)[0]
                else:
                    request_body[prop_name] = fake.text(max_nb_chars=255)
            elif prop_details["type"] == "boolean":
                request_body[prop_name] = True
            elif prop_details["type"] == "integer":
                request_body[prop_name] = 1
            elif prop_details["type"] == "number":
                request_body[prop_name] = 1.0
            elif prop_details["type"] == "array":
                request_body[prop_name] = []
            elif prop_details["type"] == "object":
                request_body[prop_name] = {}
            else:
                print(f"Unknown type {prop_details['type']} for {prop_name}")

    print(request_body)
    return request_body


# https://stackoverflow.com/a/48407739 Joe Iddon
def disp_paths(it, p='$'):
    result = []
    for k, v in (it.items() if type(it) is dict else enumerate(it)):
        if type(v) is dict:
            disp_paths(v, '{}.{}'.format(p, k))
        elif type(v) is list:
            for i, e in enumerate(v):
                if type(e) is dict or type(e) is list:
                    result.extend(disp_paths(e, '{}.{}[{}]'.format(p, k, i)))
                else:
                    result.append(('{}.{}[{}]'.format(p, k, i), e))
        else:
            f = '{}.{}' if type(it) is dict else '{}[{}]'
            result.append((f.format(p, k), v))
    return result


@click.command()
@click.option("--fix", "-f", is_flag=True, help="Fix the API state and save responses as asserts in hurl files.")
@click.option("--env", "-e", is_flag=False, help="env file to process.")
def main(fix, env):
    global ignore_paths
    i = 0
    requested = []
    read_dotenv(env)

    if fix:
        ignore_path = ".hurlignore"
        if os.path.exists(ignore_path):
            # print(f"Found {ignore_path}")
            with open(ignore_path) as f:
                ignore_paths = f.readlines()
                ignore_paths = [x.strip() for x in ignore_paths]

        os.system(f"rm {tests_dir}/*.hurl")

        os.makedirs(tests_dir, exist_ok=True)
        os.system(f"rm {tests_dir}/*.hurl")
        HOST = "http://localhost"
        schema_yaml = requests.get(f"{HOST}:{os.environ['PORT']}/{os.environ['BASE_URL']}/schema/").content
        schema = yaml.safe_load(schema_yaml)

        # Convert to JSON
        json_data = json.loads(json.dumps(schema))

        # Resolve JSON references
        schema = jsonref.JsonRef.replace_refs(json_data)

        pprint(schema)

        base_url = HOST + ":" + os.environ["PORT"]

        # Read tokens from files
        token_files = glob.glob(f"{tokens_dir}/*.jwt")
        tokens = {"unauthenticated": ""}
        for token_file in token_files:
            with open(token_file, 'r') as f:
                role = os.path.basename(token_file).split('.')[0]
                tokens[role] = f.read().strip()  # assuming each file only contains the token

        for path, methods in schema["paths"].items():
            for method, details in methods.items():
                operation_id = details["operationId"]

                for user_type, token in tokens.items():
                    uri_raw = f"/{os.environ['BASE_URL']}{path}"

                    uri_params = regex.findall(r"\{.[^}]+\}", uri_raw)

                    uris = [(uri_raw, {})]

                    for uri_param in uri_params:
                        uri_param_data = lookup_variable_value(uri_param)

                        uris = [(re.sub(r"\{.[^}]+\}", uri_param_data, uri), {uri_param: uri_param_data}) for
                                uri_param_data in uri_param_data for uri, params in uris]

                    filename = f"{tests_dir}/{i:03d}_{operation_id}_{user_type}.hurl"
                    i += 1

                    for uri, param in uris:
                        url = f"{base_url}{uri}"

                        headers = {"Authorization": f"Bearer {token}",
                                   'content-type': 'application/json'}
                        if not token:
                            del headers["Authorization"]

                        # Handle query parameters
                        if 'parameters' in details:
                            query_params = [p for p in details['parameters'] if p['in'] == 'query']
                            param_combinations = []
                            for p in query_params:
                                param_name = p['name']
                                with open(f"{value_dir}{param_name}", "r") as file:
                                    param_values = file.read().split()
                                    param_values += ['']
                                param_combinations.append([(param_name, value) for value in param_values])
                            all_param_combinations = list(itertools.product(*param_combinations))

                            for params in all_param_combinations:
                                params_str = "&".join(f"{k}={v}" for k, v in params[:2] if v)
                                url_with_params = url + ("?" + params_str if params_str else "")

                                requested_url = method + url_with_params + user_type
                                if requested_url in requested:
                                    continue
                                requested.append(requested_url)
                                make_request_and_record_assertion(filename, method, url_with_params, headers, user_type,
                                                                  details,
                                                                  param)

                        else:  # If no parameters are needed
                            make_request_and_record_assertion(filename, method, url, headers, user_type, details, param)

    else:
        os.system(f"hurl --test --fail-at-end  {tests_dir}/*.hurl ")


def lookup_variable_value(uri_param):
    try:
        with open(f"{value_dir}{uri_param}", "r") as file:
            uri_param_data = file.read().split()
        return uri_param_data
    except FileNotFoundError:
        return None


if __name__ == "__main__":
    main()
```

At the moment it consumes the schema from the API (I just pass an .env file to let it know, where it is) and values from some directory, to create request bodies, request parameters and tries out different authentication modes:

```
.
├── main.py
├── tests
│   ├── 000_[openApi-operation_id_0]_unauthenticated.hurl
│   ├── 001_[openApi-operation_id_0]_admin.hurl
│   ├── 002_[openApi-operation_id_0]_user.hurl
...
│   └──nnn_[openApi-operation_id_n]_user.hurl
├── tokens
│   ├── admin.jwt
│   └── user.jwt
└── values
    ├── body_value  <- value to fill up dummy request body
    └── {userId}       <- value to try out request params
```

a hurl file created by it is:

```
PUT http://localhost:8002/spass/v1/.../1/

Authorization: Bearer ey...

{
  "...": {
    "id": "1",
    "xxx": "public",
    "???": "aabbccdd-c158-4504-b273-25031bfa4290"
  },
  "any_string_without_a_value_given": "Decision black western myself scientist tough everything kind. Pick church recent high opportunity cause property. Place score design major maybe manage.\nFeel seat appear perform agent likely. Suffer without rather."
}
```
The text is generated with faker.

### Proposal

I would like to integrate this into hurl and let it run in rust and do this test generation from openApi-schemas.

Useful for this would be some templating language for this. That you give the tool a "hurl -template" and some folder containing folders for query params, body params and jwt-tokens to try on the api and that it nows, where to put them. This could be controlled outside of the implementation in hurl to allowed for custom headers.

It should do some kind of api snapshots that are constant and only regenerate parts of the files, that are failing, if a test failes now and that means, the api changed.

### Additional context and resources

If you would find this nice, could you open up your mind for details of features or implementation?

### Tasks to complete

- [ ] Create a fork and add code to packages?
- [ ] How could the cli-parameter be named to trigger test generation? `hurl --generate-api-tests {schema_url} {value_folder}
- [ ] Is it fine to have a folder with values to fill the hurl template and no yaml or json?
- [ ] I have some additional file ".hurlignore" for ignoring some parts in the json, that the api returns. All json-properties from api responses with those names are ignored.

**Comment by jcamiel** [comment]
Hi, thanks for you (very long) detailed use case!
Your use case is interesting but besides Hurl core features. We [have deliberately make a simple text based format](https://github.com/Orange-OpenSource/hurl/blob/master/CONTRIBUTING.md#hurl-core-values) so complex tests can be generated with custom scripts like yours. So considering the cli tool only, I think it will not fit with Hurl. 

That said, I've two proposals:

- all the Hurl capabilities are exposed through "crates" (programmatic library in the Rust world). So what could be done is to use the crate [hurl](https://crates.io/crates/hurl) to make a tool to produce and execute Hurl tests from OpenAPI specs. This way you could do what you want, and even use [Tera templates](https://github.com/Keats/tera) (another Rust crate) to support custom templating

- add native support for JSON schemas in Hurl (See https://github.com/Orange-OpenSource/hurl/issues/543). This has been requested several times. This doesn't directly solve your issue to automatically create requests base on an OpenAPI spec but this could address the needs of validating APIs calls without writings a lot of tests by hand.
