### ISSUE TITLE
HTTP3/Quic Support

### ISSUE THREAD

**Issue by koalazub** [Orange-OpenSource/hurl#2180]
### Problem to solve

Using libcurl with http3 support for dev testing

### Proposal

* options or flags available for libcurl versions with http3 available.

`hurl --http3-only -k server.hurl`  
Note: `-k` being a flag for insecure.

* Another option is to provide the capability within the `.hurl` file. 

```hurl
GET https://localhost.com:8008
HTTP/3
```

### Additional context and resources

CLI command is:
`curl --http3-only https://localhost:8008/dev`

Or insecure(certs not yet valid)
`curl --http3-only -k https://localhost:8008/dev`

### Tasks to complete

- [ ] Check the feature list of the libcurl version being used
- [ ] Provide flags if available
- [ ] Handle errors if not available

### Note

As I understand it, HTTP3 hasn't yet been finalised. So fair enough if this is something to not yet be implemented

**Comment by jcamiel** [comment]
Hi @koalazub 

HTTP/3 support is available on master (see #1155), and will be available in the next Hurl release (4.2.0). If you know how to build Hurl with Rust tooling, you can test it right now.

Note: as Hurl uses curl for the HTTP engine, Hurl supports HTTP/3 only if your libcurl supports it.
You can see what features are available with `--version`:

```shell
$ hurl --version
hurl 4.1.0 (x86_64-apple-darwin23.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets
Features (built-in): brotli
````
