### ISSUE TITLE
Generate html report directory structure (mkdir -p)

### ISSUE THREAD

**Issue by OverkillGuy** [Orange-OpenSource/hurl#2531]
### Problem to solve

Generating test results in CI, the pattern I'm used to is a cross-tool `test_results/` folder, in which we get a `junit/` subfolder for junit-ish XML, a `coverage/` folder for all coverage-related matters, and now a `hurl/` subfolder for all hurl's output, mostly HTML. This looks like this:

```
test_results
├── coverage
│   ├── coverage.html
│   └── coverage.xml
├── hurl
│   └── index.html
└── junit
    ├── hurl_end2end.xml
    └── unit_results.xml
```

Note that the `test_results/` folder doesn't exist in repo, it's generated by the first command that runs.
In CI during integration tests, that's `hurl` during the HTML report, but instead I get:
> error: HTML dir test_results/hurl can not be created

Because I'm missing `test_results/` root.
Note of course I could just create a `.gitkeep` empty file in that folder to keep it created, but I feel it's common to expect testing tools to be able to create result folders?

### Proposal
Suggest enabling report-path creation like `mkdir -p` would, when given a report path that has missing parents, instead of crashing.

I'd personally expect this behaviour to be the default, but it's possibly surprising people, so maybe expose it as `--mkdir-report` flag if it's deemed unsafe by default.

### Additional context and resources

Change in code might be as simple as changing this:

https://github.com/Orange-OpenSource/hurl/blob/2cac54911eb816ef7e3222d292a0269d8303ce7d/packages/hurl/src/cli/options/matches.rs#L157

```diff
-             match std::fs::create_dir(path) {
+             match std::fs::create_dir_all(path) {
```

### Tasks to complete
- [x] Confirm we want this behaviour
- [ ] Determine if there are more code paths affected
- [ ] Determine if we need a flag for this instead of defaulting to it
- [ ] Do the change
- [ ] Testing to confirm no threading surprise etc

**Comment by jcamiel** [comment]
Hi @OverkillGuy 

Thank you for you detailed issue. It seems reasonable to me to create any intermediate subdirectory, it should be the default. I don't see any problem to implement it (I will check with the others maintainers),

Thanks!

**Comment by jcamiel** [comment]
Hi @OverkillGuy 

This should be fixed now by #2555, will be available in Hurl 4.3.0.

Thanks for the report,
