### ISSUE TITLE
Semantic JSON assertion

### ISSUE THREAD

**Issue by marcodpt** [Orange-OpenSource/hurl#2835]
### Problem to solve

Firstly, I would like to thank this wonderful project and the efforts of its developers in the open source community.

I consider HURL excellent for testing Rest API.

However, the tests themselves could function as documentation if written well.

One of the things that prevents me from doing this is being forced to put unformatted JSON in the tests.

Another problem that it generates is that any ordering change in the properties and we have to correct all the tests.

These seem like simple problems, but they become serious and impeding as the number of tests increases and the complexity of the JSON API data increases.

This problem has already been mentioned and discussed: #272 #270 

### Proposal

My proposal is to ignore the problem of semantic validation of XML for now and start by solving the problem of semantic validation of JSON.

Libraries like serde json create the Value structure that allows you to compare JSON semantically.

Multiline body starting with ```json should be parsed with the library and the server response as well.

```rust
assert_eq!(
    test_multi_line_json.parse::<serde_json::Value>().unwrap(),
    server_response.parse::<serde_json::Value>().unwrap()
);
```

### Additional context and resources

[serde_json](https://github.com/serde-rs/json)

[JSON semantic compare in rust](https://stackoverflow.com/questions/75904211/in-rust-tests-how-to-assert-eq-some-json-that-keeps-reordering-its-keys)

### Tasks to complete

- [ ] parse with serde json the expected multiline JSON defined in tests.hurl
- [ ] parse the response body 
- [ ] in case of any error of parsing the test fail
- [ ] compare both `Value` with the simple eq operator in rust

**Comment by jcamiel** [comment]
Hi @marcodpt 

We're currently preparing the work for better error reporting and this work is the route to semantic difference.
A first batch of refacto is to be able to able to show better diff with multiline ```

The multiline check will not be semantic, whereas the JSON (and XML) body will be semantic. This way, user could choose to have semantic or "raw" diff.

To be clear (unless I'm mistaken of what we want @fabricereix )


# Not semantic, raw diff, whitespaces sensitive:

~~~
GET https://foo.com/json
HTTP 200
```json
{ 
  "bar": true
}
```
~~~

~~~
GET https://foo.com/csv
HTTP 200
```
aaa,bbb,ccc
aaa,bbb,ccc
```
~~~

=> current work is to improve the error diag

# Semantic, whitespaces unsensitive:

~~~
GET https://foo.com/json
HTTP 200
{ 
  "bar": true
}
~~~

**Comment by jcamiel** [comment]
Yes it makes sens

**Comment by fabricereix** [comment]
We could use the same output as [jd](https://github.com/josephburnett/jd)
