### ISSUE TITLE
Proxy SOCKS support

### ISSUE THREAD

**Issue by linkdd** [Orange-OpenSource/hurl#3311]
### Problem to solve

```bash
ssh -D8080 user@host

curl --socks5 localhost:8080 https://httpbin.org/anything
```

### Proposal

~In the `[Options]` section, the `proxy` field should be a URL, such as:~

 - `http://localhost:8012`
 - `socks5://localhost:8012`
 - ...

~The scheme of the URL could then be used to determine the type of proxy (no scheme would default to HTTP for backward compatibility) we want to connect to.~

~Then, we should be able to connect to SOCKS proxy as demonstrated with cURL above.~

> **EDIT:** Let's add instead a `sock5` request option with the host and port of the SOCKS proxy to use.

### Additional context and resources

We are using Hurl to implement the test suite of a Reverse Proxy service we provide in our infrastructure. Its configuration is pulled from [Netbox](https://netbox.dev). One feature is the Access Control Lists, which translates to the following NGINX configuration:

```nginx
server {
  # ...

  location / {
    # ...

    deny 192.168.2.0/24;
    allow all;

    # ...
  }

  # ...
}
```

The test we want to execute is the following:

```hurl
# Rejection when coming from 192.168.2.0/24
GET https://example.com

HTTP 403

# No rejection when coming from 127.0.0.1/8
GET https://example.com
[Options]
socks5: localhost:8012

HTTP 200
```

### Tasks to complete

 - [x] ~Support URLs in `proxy` request option~
 - [ ] Add `socks5` request option
 - [ ] Support Proxy SOCKS protocol

**Comment by jcamiel** [comment]
Hi @linkdd 

I think I prefer to have a dedicated `socks5` option to match _excatly_ the curl option name

```hurl
GET https://example.com
[Options]
socks5: localhost:8012
HTTP 200
```

**Comment by linkdd** [comment]
Sounds good to me. But what would be the behavior when we define both `proxy` and `socks5` fields then? Should it be an error?

**Comment by jcamiel** [comment]
Yes we can check what is the behavior of curl in this case and try to match it.

**Comment by linkdd** [comment]
Ok, I updated the issue description accordingly.

It seems the `curl` crate you use already provides everything needed, the `Easy2::proxy()` function ([docs](https://docs.rs/curl/0.4.47/curl/easy/struct.Easy2.html#method.proxy)) seems to accept URLs of the form `socks5://host:port`, which correspond to the `CURLOPT_PROXY` option.

**Comment by jcamiel** [comment]
@linkdd Reviewing the code, I see that we have no restriction on urls passed to `proxy` option.

Could you try this syntax ?

```
# Rejection when coming from 192.168.2.0/24
GET https://example.com
HTTP 403

# No rejection when coming from 127.0.0.1/8
GET https://example.com
[Options]
proxy: socks5://localhost:8012
HTTP 200
```

**Comment by linkdd** [comment]
Indeed, it works 🙂

Another case of [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC).

I'm closing the issue.
